version: '2.4'
services:

    web:
        image: nfqlt/apache24-fastcgi
        ports:
            - '10.24.1.17:80:80'
        links:
            - fastcgi
        volumes:
            - './src:/home/project/src'
        environment:
            NFQ_PROJECT_ROOT: /home/project/src
            NFQ_ENABLE_APACHE_MODULES: rewrite

    fastcgi:
        image: nfqlt/php72-fpm
        links:
            - postgres
        volumes:
            - './src:/home/project/src'
        environment:
            NFQ_PROJECT_ROOT: /home/project/src
            NFQ_ENABLE_PHP_MODULES: 'curl json pdo gd mcrypt ctype tokenizer simplexml intl opcache soap mbstring xml zip dom xmlwriter xmlreader iconv posix tidy fileinfo ftp exif bcmath xdebug sqlite3 pdo_sqlite mailparse'

    postgres:
        image: postgres
        ports:
            - '10.24.1.17:5432:5432'
        volumes:
            - /var/lib/postgresql/data
        command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all -c max_connections=200
        environment:
            POSTGRES_USER: postgres

### uncomment if it's required ###
#    pgadmin:
#        environment:
#            - "POSTGRES_USER=postgres"
#            - "PGADMIN_DEFAULT_EMAIL=admin@admin.com"
#            - "PGADMIN_DEFAULT_PASSWORD=pgpasswd"
#        ports:
#            - '10.24.1.17:5050:80'
#        image: dpage/pgadmin4
#        depends_on:
#            - postgres
###

    https-dev:
        image: nfqlt/https-dev
        ports:
            - '10.24.1.17:443:443'
        links:
            - web

    dev:
        image: nfqlt/php72-dev
        ports:
            - '10.24.1.17:22:22'
        links:
            - postgres
        volumes:
            - './src:/home/project/src'
            - '/home/project/.ssh:/home/project/.ssh'
            - '/etc/ssh:/etc/ssh'
            - '/etc/environment:/etc/environment-vm:ro'
        environment:
            NFQ_ENABLE_PHP_MODULES: 'url json pdo gd mcrypt ctype tokenizer simplexml intl opcache soap mbstring xml zip dom xmlwriter xmlreader iconv posix tidy fileinfo ftp exif bcmath xdebug sqlite3 pdo_sqlite mailparse'
            NFQ_PROJECT_ROOT: /home/project/src
#            NFQ_INIT_SCRIPT: develop_init.sh correct path
            NFQ_INIT_SCRIPT: /tools/develop_init.sh

    linker:
        image: nfqlt/linker18ce
        volumes:
            - '/run/docker.sock:/run/docker.sock'

volumes: {  }

networks:
    default:
        ipam:
            config:
                -   subnet: 10.24.1.17/28
